[package]
name = "wallman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image="0.24.3"
reqwest={verstion="0.11.11", features=["blocking"]}
home="0.5.3"
