local dir = os.getenv('HOME') .. '/.config/awesome/icons/'

return {
  power = dir .. "power.svg",
  restart = dir .. "restart.svg",
  sleep = dir .. "power-sleep.svg",
  logout = dir .. "logout.svg",
  default = dir .. "account.png",
  lock = dir .. "lock.svg",
  volume = dir .. "volume.svg",
  posture = dir .. "heart.svg",
  logo = dir .. "arch.svg",
  clock = dir .. "clock.svg",
  keyboard = dir .. "keyboard.svg",
  macros = dir .. "macro.svg",
  bell = dir .. "bell.svg",
  bell_slash = dir .. "bell-slash.svg",
  launcher = dir .. "launcher.svg",
  calendar = dir .. "calendar.svg",
  volume_high = dir .. "volume-high.svg",
  volume_medium = dir .. "volume-medium.svg",
  volume_low = dir .. "volume-low.svg",
  volume_mute = dir .. "volume-mute.svg",
  window_minimize = dir .. "window-minimize.svg",
  notification_center_open = dir .. "notification-center-open.svg",
  notification_center_close = dir .. "notification-center-close.svg",
}
