---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jakub.
--- DateTime: 7/16/22 3:01 PM
---
local beautiful = require("beautiful")
local awful = require("awful")

client.connect_signal("request::manage", function(c)
    function c:maximize()
        local sc = awful.screen.focused()
        if sc ~= nil then
            self.x = sc.geometry.x
            self.y = sc.geometry.y
            self.width = 1920
            self.height = 1080 - Beautiful.bar.barHeight
        end
    end

end)
